import = ["/home/will/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[font.bold]
family = "VictorMono Nerd Font"
style = "Bold"

[font.italic]
family = "VictorMono Nerd Font"
style = "Italic"

[font.normal]
family = "VictorMono Nerd Font"
style = "Medium"

[font.glyph_offset]
y = 0
x = 0

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mods = "Shift"

[mouse]
hide_when_typing = true

# [mouse.double_click]
# threshold = 300

# [mouse.hints.launcher]
# args = []
# program = "xdg-open"

# [mouse.triple_click]
# threshold = 300

[window]
opacity = 0.85
startup_mode = 'Maximized'
decorations = "None"
blur = true

[window.padding]
x = 0
y = 0
