[git_branch]
format="  [$symbol$branch]($style) "
symbol = " "
style="bold #61afef"

[git_status]
format='([$all_status$ahead_behind]($style) )'
modified="[$count](bold yellow)"
untracked="$count"
ahead = "[⇡$count](bold green)"
behind = "⇣${count}"
