gui:
  theme:
    activeBorderColor:
    - blue
    inactiveBorderColor:
    - black
    selectedRangeBgColor:
    - reverse
    - black
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
