gui:
  sidePanelWidth: 0.2 # number from 0 to 1
  parseEmoji: true
  showIcons: true
  theme:
    activeBorderColor:
    - blue
    inactiveBorderColor:
    - black
    selectedRangeBgColor:
    - reverse
    - black
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
